### ISSUE TITLE
AttributeError: _RSAobj object has no 'export_key' attribute

### ISSUE THREAD

**Issue by RahulHackz** [nathan-149/CustomCrypocurrency#14]
I always get this error while signing up :-(

**Comment by noisycat05** [comment]
Hmm. That's odd. I actually just reviewed that code. It has to do with the pycrypto package where the keys are generated.
I will take a look around and see if I can recreate your issue.

**Comment by noisycat05** [comment]
#5 Should fix the issue! Or if you want to fix it yourself in the code, look for blockchain.py and search for all of the instances of "export_key" and just change it to "exportKey".

**Comment by RahulHackz** [comment]
> #5 Should fix the issue! Or if you want to fix it yourself in the code, look for blockchain.py and search for all of the instances of "export_key" and just change it to "exportKey".

Thanks. I will try it out :-)
